### ISSUE TITLE
Accreditamento Fornitore A1#111ADSFINMATIC - Data_Processing_SPA - SmartHealth - 4.5.048

### ISSUE THREAD

**Issue by adal72** [ministero-salute/it-fse-accreditati#29]
Salve, in data 07/08/2023 il Team FSE 2.0 (fse_support@sogei.it) ci ha comunicato il superamento dei test da noi eseguiti e l'esonero dei Test non applicabili nel nostro sistema. Ci ha anche avvisato che "A conclusione del processo, seguirà ulteriore comunicazione da parte del Dipartimento per la Trasformazione Digitale (DTD).".
Per pianificare il dispiegamento dai clienti interessati, ci chiediamo:
- dobbiamo attendere questa ulteriore comunicazione ?
- quando il nostro sistema verrà incluso in questa lista ? https://github.com/ministero-salute/it-fse-accreditati/tree/main/RESULTS
Grazie.

**Comment by adal72** [comment]
scusate il refuso volevo scrivere 07/06/2023 e non 07/08/2023

**Comment by zukka77** [comment]
Esatto, dovrebbe arrivare comunicazione per l'ok o eventuali richieste di chiarimenti per i casi di non applicabilità.
Dopodiché il software sarà aggiunto alla lista.
Ricordo che il canale "monitorato" per gli issue è quello su fse-support https://github.com/ministero-salute/it-fse-support/issues

**Comment by adal72** [comment]
Graie Andrea, confermo abbiamo ricevuto richiesta di ulteriori chiarimenti in data 16/06 e abbiamo già risposto:
https://github.com/ministero-salute/it-fse-accreditamento/pull/599
attendiamo fiduciosi !!!!

**Comment by medicalmarena** [comment]
Salve come faccio ad iscrivermi in questa lista?

**Comment by zukka77** [comment]
@medicalmarena puoi partire da qui per il contesto e la procedura da seguire: https://developers.italia.it/it/fse/#fase-di-accreditamento-convalida
Qui la documentazione di supporto allo sviluppo: https://github.com/ministero-salute/it-fse-support
